#!/bin/bash

# sbatch -J $1_composite_CAS -o composite_CAS_$1.out ./run_composite tile_lists/tile_$1.txt 

for i in {0..33}
do
    sbatch /explore/nobackup/people/jacaraba/development/vhr-composite/slurm/run_composite /explore/nobackup/people/jacaraba/development/vhr-composite/tile_lists/tile_$i.txt 
done
