#!/bin/bash
#SBATCH --job-name "composite"
#SBATCH --time=05-00:00:00
#SBATCH -G 1
#SBATCH -c10
#SBATCH --mem-per-cpu=10240
#SBATCH --mail-user=jordan.a.caraballo-vega@nasa.gov
#SBATCH --mail-type=ALL

module load singularity

echo Starting $1

date

srun -n 1 singularity exec \
    --env PYTHONPATH="/explore/nobackup/people/jacaraba/development/tensorflow-caney:/explore/nobackup/people/jacaraba/development/vhr-composite" \
    --nv -B $NOBACKUP,/lscratch,/explore/nobackup/people,/explore/nobackup/projects \
    /explore/nobackup/projects/ilab/containers/tensorflow-caney-2023.05 \
    python /explore/nobackup/people/jacaraba/development/vhr-composite/scripts/senegal_calculate/vhr_senegal_etz_grid_by_epoch_no_filtering.py $1

date

echo Done $1

