#!/bin/bash

#SBATCH -G 1 -t 10:00:00

module load anaconda
conda activate rapids-22.10

export PYTHONPATH=$PWD:$PWD/vhr-composite

echo Starting $1

date

python vhr-composite/scripts/senegal_calculate/vhr_senegal_generate_grid.py $1

date

echo Done $1
